
# Environment Instances
instances:
  - name: "bastion"
    count: 1
    unique: true
    public_dns: true
    dns_loadbalancer: false
    image: "{{ image_type }}"
    flavor: "{{ bastion_instance_type }}"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
      - key: "ostype"
        value: "linux"
      - key: "instance_filter"
        value: "{{ env_type }}-{{ email }}"
    volumes:
      - name: '/dev/sda1'
        size: 20
    security_groups:
      - BastionSG

  - name: "workstation"
    count: 1
    public_dns: false
    dns_loadbalancer: false
    image: "{{ image_type }}"
    flavor: "{{ workstation_instance_type }}"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
      - key: "ostype"
        value: "linux"
      - key: "instance_filter"
        value: "{{ env_type }}-{{ email }}"
    security_groups:
      - DefaultSG

  - name: "hypervisor"
    count: 1
    public_dns: false
    dns_loadbalancer: false
    image: "{{ image_type }}"
    flavor: "{{ hypervisor_instance_type }}"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
      - key: "ostype"
        value: "linux"
      - key: "instance_filter"
        value: "{{ env_type }}-{{ email }}"
    security_groups:
      - DefaultSG

install_ipa_client: false
install_bastion: false
install_common: false

set_env_authorized_key: true
env_authorized_key: "{{guid}}key"

deploy_local_ssh_config_location: "{{output_dir}}/"

project_tag: "{{ env_type }}-{{ guid }}"

# repo_method: file # Do not set this, or it breaks on RHEL8 images

update_all_packages: false
