---
# sample configuration file 
#
# Usage: ansible-playbook main.yml -e @configs/just-some-nodes-example/sample.yml
#
# Ideally keep your copy OUTSIDE your repo, especially if using Cloud Credentials

env_type: just-some-nodes-example       # Name of config to deploy
output_dir: /tmp/workdir                # Writable working scratch directory
node_instance_count: 2                  # Number of nodes to deploy
email: name@example.com                 # User info for notifications

guid: guid02                             # Unique string used in FQDN
subdomain_base_suffix: .example.opentlc.com      # Your domain used in FQDN

# Path to yum repos
own_repo_path: http://admin.example.com/repos/version

# Cloud specfic settings - example given here for libvirt

cloud_provider: libvirt                   
infra_libvirt_hostname: superone                

key_name: libvirt


